name = "SymplecticFactorizations"
uuid = "7425e8e4-4cde-4e45-9b2f-a15679260f9b"
authors = ["Andrew Kille"]
version = "0.1.7-dev"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.9"
julia = "1.6.7, 1.10.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
